reg_login/blogs/urls.py
from django.urls import path
from . import views

app_name = 'blogs'
urlpatterns = [
    path('',views.all_blogs,name="BlogsPage"),
    path('<int:user_id>/',views.user_blogs,name="UserBlogs"),
    path('CreateBlogPost/',views.create_blog,name="CreateBlog"),
    path('blog/<str:title>/',views.blog_post,name="BlogPost"),
    path('<str:title>/delete',views.delete_blog,name="delete"),

]

reg_login/main/urls.py
from django.urls import path
from .views import home,reg,logout_page,news
from django.contrib.auth import views as auth_views

app_name = 'main'
urlpatterns = [
    path('', home, name="Home"),
    path('news/', news, name="News"),
    path('reg/', reg, name="Reg"),
    path('login/', auth_views.LoginView.as_view(template_name='main/login.html'), name='Login'),
    path('logout/', logout_page, name="logout"),
]

reg_login/reg_login/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf import settings
from django.conf.urls.static  import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('main.urls')),
    path('blogs/',include('blogs.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

reg_login/blogs/models.py
from django.db import models
from django.contrib.auth.models import User

from django.dispatch import receiver
from django.db.models.signals import post_delete
import os
# Create your models here.
class BlogPost(models.Model):
    title = models.CharField(max_length=250,unique=True,null=False,blank=False)
    summary = models.TextField()
    posted_at = models.DateTimeField(auto_now_add=True)
    posted_by = models.ForeignKey(User,on_delete=models.CASCADE, related_name='related_blogs')
    image_small = models.ImageField(upload_to='images/',null=True,blank=True)

    def __str__(self):
        return f"{self.title} - {self.posted_by.username}"
    
    class Meta:
        ordering = ('-posted_at',)
    
class CommentModel(models.Model):
    comment = models.CharField(max_length=150)
    image = models.ImageField(null=True,blank=True)
    comment_by = models.ForeignKey(User,on_delete=models.CASCADE)
    comment_on = models.ForeignKey(BlogPost,on_delete=models.CASCADE,related_name='blog_comments')
    comment_at = models.DateTimeField(auto_now=True)
    
@receiver(post_delete, sender=BlogPost)
def delete_media_file_on_delete(sender, **kwargs):
    instance = kwargs['instance']
    if instance.image_small:
        with open(instance.image_small.path, 'r'):
            pass
        os.remove(instance.image_small.path)

class Query(models.Model):
    query = models.CharField(max_length=250)
    

reg_login/blogs/forms.py
from django import forms
from .models import BlogPost,CommentModel,Query

class NewBlogForm(forms.ModelForm):
    class Meta:
        model = BlogPost
        fields = ('title','summary','image_small',)

class commentForm(forms.ModelForm):
    class Meta:
        model = CommentModel
        fields = ('comment',)


class searchForm(forms.ModelForm):
    class Meta:
        model = Query
        fields = ('query',)

reg_login/blogs/views.py
from django.shortcuts import get_object_or_404, redirect, render
from .models import BlogPost
from .forms import NewBlogForm,commentForm,searchForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
# Create your views here.
def all_blogs(request):
    recent_blogs = BlogPost.objects.all()
    #searchbar
    form=searchForm()
    if request.method == 'POST' and form.is_valid:
        form = searchForm(request.POST)
        form.save(commit=False)
        query = form.cleaned_data['query']
        matching_blogs = BlogPost.objects.filter(title__icontains = query)
        return render(request,'blogs/all_blogs.html',{'matching_blogs':matching_blogs})
    return render(request,'blogs/all_blogs.html',{'recent_blogs':recent_blogs})

def create_blog(request):
    if not request.user.is_authenticated:
        return render(request,'main/login.html',{'message':"Log in to post blogs"})
    form = NewBlogForm()
    if request.method == 'POST':
        form = NewBlogForm(request.POST,request.FILES)
        if form.is_valid:
            blog = form.save(commit=False)
            blog.posted_by = request.user
            if 'image_small' in request.FILES:
                image = request.FILES['image_small']
                blog.image_small = image

            blog.save()
            return redirect('blogs:BlogsPage')
        return render(request,'blogs/CreateBlogPage.html')
    return render(request,'blogs/CreateBlogPage.html',{'form':form})

def blog_post(request,title):
    blog = get_object_or_404(BlogPost,title=title)
    comment = commentForm()
    comment.comment_on = title
    #posting comments
    if request.method == 'POST':
        comment = commentForm(request.POST,request.FILES)

        if comment.is_valid:
            comment = comment.save(commit=False)
            comment.comment_by = request.user
            comment.comment_on = BlogPost.objects.get(title=title)
            
            if 'image' in request.FILES:
                image = request.FILES['image']
                comment.image = image
                print('*************************')
                if comment.image:
                    print("IMAGE SAVED!!!!")
            comment.save()
            all_comments = blog.blog_comments.all()
            return render(request, 'blogs/BlogPage.html',{'blog':blog,'all_comments':all_comments})

        else:
            all_comments = blog.blog_comments.all()
            error = "The only kind of file you are allowed to upload are images."
            return render(request, 'blogs/BlogPage.html',{'blog':blog,'error':error,'all_comments':all_comments})


    else:
        all_comments = blog.blog_comments.all()
        return render(request, 'blogs/BlogPage.html',{'blog':blog,'all_comments':all_comments})

def user_blogs(request,user_id):
    if not request.user.is_authenticated:
        return render(request,'main/login.html',{'message':"Log in to proceed."})
    user = get_object_or_404(User,id=user_id)
    user_blogs = user.related_blogs.all()
    return render(request,"blogs/user's_blogs.html",{'user_blogs':user_blogs,'Blogger':user.username})

#delete blog
@login_required
def delete_blog(request,title):
    blog = get_object_or_404(BlogPost,title=title)
    blog.delete()

    return render(request,"blogs/user's_blogs.html",{'message':"Blog deleted successfully!"})

reg_login/blogs/templates/blogs/BlogPage.html
{% extends "main/base.html" %}
{% block  title %}Blogs{% endblock  %}
{%block content%}

<div class="container bg-gray-50 my-32 mx-auto px-3 py-3 shadow-2xl w-3/4 text-wrap">

   <div class='relative'>
    <a href="{% url 'blogs:UserBlogs' user_id=blog.posted_by.id %}" class="mx-auto font-mono font-extrabold text-red-500 hover:underline">{{blog.posted_by}}</a>
<!--delete blog-->
    {% if request.user.is_authenticated and request.user == blog.posted_by %}
        <a href="{% url 'blogs:delete' blog.title %}" class='absolute top-0 right-0 px-2 py-1 ring-4 ring-red-500 hover:bg-red-600 hover:duration-200 bg-red-200 font-mono font-bold hover:text-white'>Delete Blog</a>
    </div>
    {% endif%}

    <h1 class="mx-auto font-mono font-extrabold text-lg text-wrap">{{blog.title}}</h1>


<!--Display image-->
    {%if blog.image_small%}
    <div class="w-full h-auto rounded-lg"><img src="{{blog.image_small.url}}" alt="Blog Image"></div>
    {% endif %}
    <div class="font-sans text-wrap">{{blog.summary}}</div>
</div>
</div>
<!--Comment Section-->

    <div class="container bg-gray-700 my-4 mx-auto  rounded-xl px-3 py-3 shadow-2xl w-3/4">
        <p class="font-sans font-extrabold text-lg text-white">Comment Section</p>

        {% if request.user.is_authenticated %}
            <form method="post" action='.' enctype='multipart/form-data' class='py-3 px-2'>
                {% csrf_token %}
                <textarea rows="3" id="user-input" class='py-3 px-2 w-full' name='comment' placeholder='Comment on the Blog'></textarea>
                <input type='file' class='py-3 ' accept='image/*' name='image'><br>
                <button type='submit' class="bg-white py-1 px-2 rounded-sm">Submit</button>
            </form>
        {% if error %}{{error}}{% endif %}
        {%else%}
        <p class='text-white'><a href="{%url 'main:Login' %}" class='hover:bg-white hover:text-black rounded-xl hover:duration-300 p-1 underline'>Log in </a>to comment on this blog.</p>
    {% endif%}

        {% for each_comment in all_comments%}
            <div class="text-white my-2 rounded-xl px-2 relative">
                <p class='text-red-400'>{{each_comment.comment_by}}</p>
                <p class='absolute top-0 right-4 text-sm'>{{each_comment.comment_at}}</p>
                {% comment %} <button style="font-size:24px;color:red;"><i class="fa fa-trash-o absolute top-0 right-0"></i></button><!--delete comment--> {% endcomment %}
                {{each_comment.comment}}<br>
                {% if each_comment.image%}
                    <img src="{{each_comment.image.url}}" alt="Comment Image" class='h-28 w-28 py-1'>
                {% endif%}
            </div>
            <br>
        {%endfor%}<br>


    </div>

{%endblock%}

reg_login/blogs/templates/blogs/CreateBlogPage.html
{% extends "main/base.html" %}
{% block  title %}Create a Blog!{% endblock  %}

{%block content%}

<div class="my-32 mx-auto rounded-xl px-3 py-3 shadow-2xl w-3/4">
    <p class="font-mono text-6xl text-center">Create and Post a Blog</p>
    <form method='post' action='.' enctype="multipart/form-data">
        {% csrf_token %}
        <div class="flex flex-col gap-3 my-2">

       <input type="text" name="title"  placeholder="Enter Title For Your Blog" class = "btn-gray w-full h-10 py-3 px-2" >
       <textarea rows="10" cols="50" id="user-input" name="summary" class = "btn-gray w-full py-3 px-2" placeholder='Enter Content'></textarea>
       <input type="file" accept="image/*" name="image_small"  placeholder="Upload image" class = "btn-gray p-2 bg-gray-50" >

       

        </div>
        <button type='submit' class="btn-gray p-2 bg-green-500 font-mono">Post</button>
    </form>
</div>
{%endblock%}

reg_login/blogs/templates/blogs/all_blogs.html
{% extends "main/base.html" %}
{% block  title %}Blogs{% endblock  %}
{%block content%}

<div class="my-auto mx-auto  rounded-xl px-3 py-3 shadow-2xl w-3/4">
    <div class='grid grid-cols-2 grid-rows-1'>
    <div class="place-content-start font-serif text-lg font-extrabold">Blogs</div>
    <div class='place-content-end ml-80'>
        <!--Blog Search Bar-->
        <form method='post' action='.'>
            {% csrf_token %}
            <input type='text' name='query' placeholder='Search blogs' class='rounded-xl p-1'>
                <button type='submit'><i class="fa fa-search"></i></button>
        </form>
    </div>
</div>
    

<!--Queried Blogs if any-->
{% if matching_blogs%}
<p class="mx-auto font-mono font-extrabold">Search Results</p>
    {%for blog in matching_blogs%}

    <a href={% url 'blogs:BlogPost' title=blog.title %}>
        <div class="grid  grid-rows-4 grid-cols-6 grid-flow-col mb-2 hover:ring-black hover:ring-4 hover:pl-3 hover:duration-300 bg-gray-200 pl-1 py-2 mt-2">

            {%if blog.image_small%}
            <div class=" row-span-4 h-20">
                <img src="{{blog.image_small.url}}" alt="Blog Image" class="h-24 rounded-lg"> 
            </div>
            {%endif%}
            <div class="font-mono font-extrabold ml-0 col-span-6 overflow-hidden text-red-600">{{blog.posted_by}}</div>
            <div class="font-mono font-extrabold ml-0 col-span-6 overflow-hidden">{{blog.title}}</div>
            <div class="font-extralight col-span-6 row-span-2 grid-flow-dense  line-clamp-2">{{blog.summary}} </div>

        </div>
    </a>
    {% endfor %}
{% endif%}
    




<!--All blogs-->
{%for blog in recent_blogs%}

<a href="{% url 'blogs:BlogPost' title=blog.title %}">
    <div class="grid  grid-rows-4 grid-cols-6 grid-flow-col mb-2 hover:ring-black hover:ring-4 hover:pl-3 hover:duration-300 bg-gray-200 pl-1 py-2 mt-2">

        {%if blog.image_small%}
        <div class=" row-span-4 h-20">
            <img src="{{blog.image_small.url}}" alt="Blog Image" class="h-24 rounded-lg"> 
        </div>
        {%endif%}
        <div class="font-mono font-extrabold ml-0 col-span-6 overflow-hidden text-red-600">{{blog.posted_by}}</div>
        <div class="font-mono font-extrabold ml-0 col-span-6 overflow-hidden">{{blog.title}}</div>
        <div class="font-extralight col-span-6 row-span-2 grid-flow-dense  line-clamp-2">{{blog.summary}} </div>

    </div>
</a>
{% endfor %}

</div>
{%endblock%}

reg_login/blogs/templates/blogs/user's_blogs.html
{% extends "main/base.html" %}
{% block  title %}My Blogs{% endblock %}
{%block content%}

<div class="my-32 mx-auto  rounded-xl px-3 py-3 shadow-2xl w-3/4">
    <h1 class="mx-auto font-mono font-extrabold">{{Blogger}}'s Blogs</h1>

    

{%for blog in user_blogs%}

        <a href="{% url 'blogs:BlogPost' title=blog.title %}">
            <div class="grid  grid-rows-4 grid-cols-6 grid-flow-col mb-2 hover:ring-black hover:ring-4 hover:pl-3 hover:duration-300 bg-gray-200 pl-1 py-2 mt-2">

            {%if blog.image_small%}
            <div class=" row-span-4 h-20">
                <img src="{{blog.image_small.url}}" alt="Blog Image" class="h-24 rounded-lg"> 
            </div>
            {%endif%}
            <div class="font-mono font-extrabold ml-0 col-span-6 overflow-hidden text-red-600">{{blog.posted_by}}</div>
            <div class="font-mono font-extrabold ml-0 col-span-6 overflow-hidden">{{blog.title}}</div>
            <div class="font-extralight col-span-6 row-span-2 grid-flow-dense  line-clamp-2">{{blog.summary}} </div>

            </div>
        </a>
{% endfor %}

</div>
{%endblock%}