reg_login/blogs/urls.py
from django.urls import path
from . import views

app_name = 'blogs'
urlpatterns = [
    path('',views.all_blogs,name="BlogsPage"),
    path('<int:user_id>/',views.user_blogs,name="UserBlogs"),
    path('CreateBlogPost/',views.create_blog,name="CreateBlog"),
    path('blog/<str:title>/',views.blog_post,name="BlogPost"),
    path('<str:title>/delete',views.delete_blog,name="delete"),

]

reg_login/main/urls.py
from django.urls import path
from .views import home,reg,logout_page,news
from django.contrib.auth import views as auth_views

app_name = 'main'
urlpatterns = [
    path('', home, name="Home"),
    path('news/', news, name="News"),
    path('reg/', reg, name="Reg"),
    path('login/', auth_views.LoginView.as_view(template_name='main/login.html'), name='Login'),
    path('logout/', logout_page, name="logout"),
]

reg_login/reg_login/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf import settings
from django.conf.urls.static  import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('main.urls')),
    path('blogs/',include('blogs.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

reg_login/main/models.py
from django.db import models

# Create your models here.

reg_login/main/views.py
from django.shortcuts import render,redirect
from django.contrib.auth import logout
from django.contrib.auth.forms import UserCreationForm
import requests

from blogs.forms import searchForm
#newsapi
from newsapi.newsapi_client import NewsApiClient

# Init
newsapi = NewsApiClient(api_key='86a49b33733d4c4298db54ce0c0d87ea')

from datetime import datetime, timedelta

# Calculate the date range for the past 30 days
to_date = datetime.now()
from_date = to_date - timedelta(days=30)

# /v2/everything
all_articles = newsapi.get_everything(q='war',
                                    sources="times-now,quint, abc-news,al-jazeera-english,ars-technica,associated-press,axios,bbc-news,bbc-sport,bleacher-report,bloomberg,business-insider,cbs-news,cnn,crypto-coins-news,engadget,entertainment-weekly,espn,ESPN,fortune,fox-news,fox-sports,google-news,hacker-news,ign,independent,mashable,medical-news-today,msnbc,national-geographic,new-scientist,newsweek,new-york-magazine,nfl-news,nhl-news,politico,recode,reddit-r-all,reuters,salon,techcrunch,techradar,the-economist,the-hill,the-huffington-post,the-new-york-times,the-verge,the-wall-street-journal,the-washington-post,time,usa-today,vice-news,wired",
                                    domains='bbc.co.uk,techcrunch.com',
                                    from_param=from_date.strftime('%Y-%m-%d'),
                                    to=to_date.strftime('%Y-%m-%d'),
                                    language='en',
                                    sort_by='relevancy',
                                    page=2)
# Create your views here.
def home(request):
    return render(request,'main/base.html')

def news(request):
    #searchbar
    form=searchForm()
    if request.method == 'POST' and form.is_valid:
        form = searchForm(request.POST or None)
        form.save(commit=False)
        query = form.cleaned_data['query']
        #api endpoint
        url = f" https://newsapi.org/v2/everything?q={query}&apiKey=86a49b33733d4c4298db54ce0c0d87ea"
        response = requests.get(url).json()
        matching_articles = response.get('articles',[])

        return render(request,'main/news.html',{'matching_articles':matching_articles})
    return render(request,'main/news.html',{'all_articles':all_articles})

def reg(request):
    if request.method == 'POST':
        
        form = UserCreationForm(request.POST)
        print('--------')
        print(form)
        if form.is_valid():
            form.save()
            return redirect('main:Login')
        else:
            errors = form.error_messages 
            return render(request,'main/reg.html',{'errors' :errors})

    else:
        form = UserCreationForm()
        return render(request,'main/reg.html',{'form':form})
    
def logout_page(request):
    logout(request)
    return redirect('blogs:BlogsPage')
    

reg_login/main/templates/main/base.html
<!DOCTYPE html>
{% load static%}
<html>

    <head>

        <style type="text/tailwindcss">
            body {
                background-image: url('{% static 'CQGWYqb.jpg' %}');
              }
            .btn-black{
                @apply hover:bg-black hover:duration-300 hover:text-white rounded-xl px-3 hover:py-3
            }
            .btn-gray{
                @apply hover:bg-gray-300 hover:duration-300 hover:text-black rounded-xl  py-2 hover:px-6
            }
            .hover-target:hover a{
                @apply bg-white text-black ring-2 ring-black
            }
            .grid-cols-4 > :hover {
                @apply bg-green-50;
              }
        </style>


        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Welcome | {%block title%}Blog site{%endblock%}</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

        <script src="https://cdn.tailwindcss.com"></script>


       
    </head>
    <body class="w-full h-screen bg-cover bg-center bg-no-repeat bg-fixed ">


        <div>

        <nav class="pt-3 font-mono shadow-lg pb-3 fixed top-0 w-full">
            
                <ul class="flex gap-5 px-3">
                  <li><a class="btn-black" href="{%url 'main:Home' %}">Home</a></li>
                  <li><a class="btn-black" href={% url 'main:News'%}>News</a></li>
                  <li><a class="btn-black" href="{% url 'blogs:CreateBlog'%}">Post a Blog</a></li>
                  <li><a class="btn-black" href="{% url 'blogs:BlogsPage' %}">Blogs</a></li>
                  
                  {%if  request.user.is_authenticated %}
                  <li><a class="btn-black" href="{% url 'blogs:UserBlogs' request.user.id %}">My Blogs</a></li>
                  <li><a class="btn-black  text-white bg-gray-600 py-2" href={% url 'main:logout' %}>Log out</a></li>
                  <li class="font-sans font-medium ml-10 absolute right-2">Welcome {{user}}</li>
                  {%else%}
                  <li ><a class="hover:bg-red-500 hover:duration-300 hover:text-white rounded-xl px-3 py-2 hover:py-3" href={% url 'main:Reg' %}>Sign Up</a></li>
                  <li><a class="hover:bg-green-500 hover:duration-300 hover:text-white rounded-xl px-3 py-2 hover:py-3" href={% url 'main:Login' %}>Log in </a></li>
                  
                  {%endif%}
                </ul>
              
        </nav>

    <br><br><br>
        
        {%block content%} 
            <h1 class='font-mono text-3xl text-center p-4'>Welcome to the Blog site</h1>

            <div class='font-mono p-10 container m-auto shadow-2xl grid grid-cols-2 grid-rows-3'>

                <section class='p-4 my-2 shadow-2xl hover-target bg-opacity-50 hover:bg-opacity-100 bg-white rounded-2xl '>
                    <h2>Ready to unleash your voice and share your story with the world? This is your chance to join the conversation! Our 'Make Your Own Blog' page is your key to unlocking a world of creative expression and self-publishing freedom. Whether you're a seasoned writer or a budding blogger, our platform is designed to help you bring your ideas to life. With our easy-to-use tools and supportive community, you'll be publishing your thoughts, experiences, and expertise in no time. So, what are you waiting for? Take the first step towards becoming a published blogger and start sharing your unique perspective with the world. Create your own blog today and let your voice be heard!</h2>
                   <br> <a class="btn-gray bg-black text-white p-2" href="{% url 'blogs:CreateBlog'%}">Make your own Blog!</a>
                </section>

                <div></div><div></div>
                <section class='p-4 my-2 shadow-2xl  hover-target bg-opacity-50 hover:bg-opacity-100 bg-purple-600 rounded-2xl'>
                    <h2 class=''>Welcome to our blogosphere! This is where the conversation gets real, and the inspiration flows. Our 'Explore Blogs' page is your gateway to a treasure trove of stories, insights, and expertise from our community of passionate writers. Dive into a world of diverse perspectives, thought-provoking ideas, and relatable experiences. Whether you're looking for advice, entertainment, or simply a fresh point of view, our blogs have got you covered. So, take a deep breath, get comfortable, and start exploring – who knows what hidden gems you might discover!</h2>
                    <br><a class="btn-gray bg-black text-white p-2" href="{% url 'blogs:BlogsPage' %}">Explore Blogs!</a>
                </section>

                <section class='p-4 my-2 shadow-2xl  hover-target bg-opacity-50 hover:bg-opacity-100 bg-blue-500 rounded-2xl'>
                    <h2>Stay ahead of the curve with the latest news and trending topics! Our news section is your one-stop shop for the most up-to-date information on the stories that matter. From breaking news and in-depth analysis to expert opinions and thought-provoking commentary, we've got you covered. Our team of dedicated writers and contributors scour the globe to bring you the most relevant, timely, and engaging news articles, so you can stay informed and make sense of the world around you. Whether you're interested in politics, entertainment, technology, or lifestyle, our news articles are designed to keep you in the know. So, what are you waiting for? Dive into the latest news and stay informed, inspired, and ahead of the curve!</h2>
                    <br><a class="btn-gray bg-black text-white p-2" href={% url 'main:News'%}>Read the Latest News Articles!</a>
                </section>
            </div>
        {%endblock%}
        
    </div>
    </body>
</html>

reg_login/main/templates/main/login.html
{% extends "main/base.html" %}

{% block title%} Log in Page{%endblock%}

{%block content%} 
<div class="bg-gray-50 my-32  mx-auto  rounded-xl px-3 py-3 shadow-2xl w-1/3 opacity-80">

<h1 class='text-center text-3xl'>{% if message%}{{message}}{%else%}Welcome to Login Page{% endif%}</h1>

<form method="POST" action="" class=" p-10 rounded-lg h-48 ">
    {% csrf_token %}

    <div>
        <label for="username"class="font-bold" >Username:</label>
        <input type='text' id='username' name="username" class="rounded-xl w-1/5 py-2 px-3 text-gray-700" placeholder="Enter your username">
    </div>
    <div class="mt-3">
        <label for="password" class="font-bold">Password:</label>
        <input type='password' id='password' name="password" class="rounded-xl w-1/5 py-2 px-3 text-gray-700 mb-3" placeholder="Enter your password">
    </div>
    <!--error-->
    {% if form.errors or form.non_field_errors %}
    <p class="text-sm">{{form.non_field_errors}}</p>
    {%endif%}
    
     <center>   <button type="submit" class="center-text font-mono bg-green-500 px-3 py-1 mt-3 rounded-xl my-2 hover:bg-black hover:text-white">
            Log in
        </button>
    </center >



    
</form>
</div>
{%endblock%}

reg_login/main/templates/main/news.html
{% extends "main/base.html" %}
{% block  title %}News{% endblock  %}

{%block content%}

<div class='bg-white w-3/4 container mx-auto my-8 px-3 bg-opacity-50 relative '>
    <!--Searchbar-->
    <form method="post" action='.' class="absolute right-0 top-0">
        {% csrf_token %}
        <input type='text' name='query' class='bg-white rounded-sm p-2 m-2'>
        <button type="submit" class='bg-green-600 font-mono mr-2 p-2'>Search</button>
    </form>
<br>
    <text class="text-lg font-mono font-bold relative left-5">World News</text>
<!--Grid-->
    <div class='grid grid-cols-3'>
    <!--Serach results-->
        {%if matching_articles%}
            {% for article in matching_articles %}
            <!--Grid cell-->
                <div class='bg-gray-200 p-6 m-1 relative hover:bg-green-600 hover:duration-300 rounded-xl'>
                    <a href={{ article.url }} target='_blank' class='text-lg font-extrabold no-underline font-mono'>
                        <p class="font-extralight">Source: {{ article.source.name }}</p>
                        {{ article.title }}
                        <img src={{article.urlToImage}} class="">
                    </a>
                </div>
            {% endfor %}
        {%else%}
        <!--Default-->
            {% for article in all_articles.articles %}
            <!--Grid cell-->
                <div class='bg-gray-200 p-6 m-1 relative hover:bg-green-600 hover:duration-300 rounded-xl'>
                    <a href={{ article.url }} target='_blank' class='text-lg font-extrabold no-underline font-mono'>
                        <p class="font-extralight">Source: {{ article.source.name }}</p>
                        {{ article.title }}
                        <img src={{article.urlToImage}} class="">
                    </a>
                </div>
            {% endfor %}
        {%endif%}
    </div>
</div>


{% endblock %}

reg_login/main/templates/main/reg.html
{% extends "main/base.html" %}

{% block title%} Registration Page{%endblock%}

{%block content%} 
<div class="bg-gray-50 my-16 mx-auto  rounded-xl px-3 py-3 shadow-2xl w-1/2 opacity-80">

        <h1 class="text-3xl"><center>Create a New Account</center></h1>
<br><br><br>

        <form method="POST" action="" class="font-bold">
            {% csrf_token %}
            <label for="username">Username:</label>
            <input type="username" id="username" name="username" class="bg-gray-400 rounded-lg px-1 py-1 my-2 mx-16"><br>
            <p class="font-mono font-light">Letters, digits and @/./+/-/_ only. </p>

            <label for="password1" >Password:</label>
            <input type="password" id="password1" name="password1" class="bg-gray-400 rounded-lg px-1 py-1 my-2 mx-16"><br>
            
            <label for="password2" >Confirm Password:</label>
            <input type="password" id="password2" name="password2" class="bg-gray-400 rounded-lg px-1 py-1 my-2"><br>

            <p class="font-light font-mono">Your password can’t be too similar to your other personal information.</p>
            <p class="font-mono font-light">Your password must contain at least 8 characters.</p>
            <p class="font-mono font-light">Your password can’t be a commonly used password.</p>
            <p class="font-mono font-light">Your password can’t be entirely numeric.</p>

            {% if errors %}
                {{errors}}
            {%endif%}

<center>
<button type="submit" class="btn-black center-text font-mono bg-green-500 px-3 py-1 mt-3 rounded-xl my-2">Register</button>
</center>     
        </form>
</div>
 {%endblock%}